package com.clearsky.weather

import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.content.Intent
import android.net.Uri
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import com.google.android.gms.location.LocationServices
import com.google.android.gms.location.Priority
import com.google.android.gms.tasks.CancellationTokenSource
import kotlinx.coroutines.*
import org.json.JSONArray
import org.json.JSONObject
import java.time.*
import java.time.format.DateTimeFormatter
import kotlin.math.*

class MainActivity : ComponentActivity() {
 private val fused by lazy { LocationServices.getFusedLocationProviderClient(this) }
 private val perm=registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){locate()}
 private val notifyPerm=registerForActivityResult(ActivityResultContracts.RequestPermission()){}
 override fun onCreate(b:Bundle?){super.onCreate(b);AlertWorker.schedule(this);WeatherStatusWorker.schedule(this);if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)notifyPerm.launch(Manifest.permission.POST_NOTIFICATIONS);setContent{App()}}
 @Composable private fun App(){val p=remember{getSharedPreferences("prefs",0)};var theme by remember{mutableStateOf(p.getString("theme","system")?:"system")};val dark=theme=="dark"||(theme=="system"&&isSystemInDarkTheme());val thirtyDays=30L*24*60*60*1000;val now=System.currentTimeMillis();val installedAt=remember{val saved=p.getLong("donation_install_time",0L);if(saved>0L)saved else now.also{p.edit().putLong("donation_install_time",it).apply()}};var donate by remember{mutableStateOf(!p.getBoolean("donation_prompt_shown",false)&&now-installedAt>=thirtyDays)};fun finishDonationPrompt(){p.edit().putBoolean("donation_prompt_shown",true).apply();donate=false};MaterialTheme(colorScheme=if(dark)darkColorScheme(primary=Color(0xFF8FCBFF),surface=Color(0xFF101820))else lightColorScheme(primary=Color(0xFF00639A),surface=Color(0xFFF6FAFD))){if(donate)DonationDialog(onDismiss={finishDonationPrompt()},onDonate={finishDonationPrompt();openUrl("https://github.com/sponsors/cpugod55")});WeatherScreen(theme){theme=it;p.edit().putString("theme",it).apply()}}}
 @Composable private fun WeatherScreen(theme:String,setTheme:(String)->Unit){
  var places by remember{mutableStateOf(readPlaces())};var search by remember{mutableStateOf(false)};var settings by remember{mutableStateOf(false)};var results by remember{mutableStateOf<List<Place>>(emptyList())};var q by remember{mutableStateOf("")};val scope=rememberCoroutineScope();val pager=rememberPagerState(pageCount={places.size.coerceAtLeast(1)})
  Scaffold(containerColor=MaterialTheme.colorScheme.surface){pad->Column(Modifier.fillMaxSize().padding(pad)){
   Row(Modifier.fillMaxWidth().padding(12.dp,8.dp),verticalAlignment=Alignment.CenterVertically){Text("ClearSky",fontSize=26.sp,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));TextButton(onClick={search=!search;settings=false}){Text(if(search)"Close" else "Locations")};TextButton(onClick={settings=!settings;search=false}){Text(if(settings)"Close" else "Settings")}}
   AnimatedVisibility(settings){Column(Modifier.padding(horizontal=16.dp,vertical=4.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Appearance",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("system" to "System","light" to "Light","dark" to "Dark").forEach{(v,l)->FilterChip(selected=theme==v,onClick={setTheme(v)},label={Text(l)})}};AboutCard()}}
   AnimatedVisibility(search){Column(Modifier.padding(horizontal=16.dp)){OutlinedTextField(q,{q=it},label={Text("City or ZIP/place name")},singleLine=true,modifier=Modifier.fillMaxWidth());Button(onClick={scope.launch{results=withContext(Dispatchers.IO){WeatherRepository.search(q)}}},modifier=Modifier.fillMaxWidth()){Text("Search")};OutlinedButton(onClick={requestLocation()},modifier=Modifier.fillMaxWidth()){Text("Use my current location")};results.forEach{r->Card(onClick={places=addSaved(r);search=false;scope.launch{pager.animateScrollToPage(places.indexOfFirst{same(it,r)}.coerceAtLeast(0))}},modifier=Modifier.fillMaxWidth().padding(vertical=3.dp)){Text("Save & view  ${r.name}",Modifier.padding(14.dp))}}}}
   if(places.isEmpty()) Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()} else HorizontalPager(state=pager,modifier=Modifier.weight(1f)){i->WeatherPage(places[i],i,places.size,{if(i>0){places=removeSaved(places[i]);scope.launch{pager.scrollToPage((i-1).coerceAtLeast(0))}}})}
   if(places.size>1) Row(Modifier.align(Alignment.CenterHorizontally).padding(7.dp),horizontalArrangement=Arrangement.spacedBy(6.dp)){repeat(places.size){i->Box(Modifier.size(if(i==pager.currentPage)8.dp else 6.dp).clip(CircleShape).background(if(i==pager.currentPage)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.outlineVariant))}}
  }}
 }
 @Composable private fun WeatherPage(place:Place,index:Int,count:Int,onDelete:()->Unit){var w by remember(place){mutableStateOf<Weather?>(null)};var err by remember(place){mutableStateOf<String?>(null)};LaunchedEffect(place){val r=withContext(Dispatchers.IO){runCatching{WeatherRepository.load(place.name,place.lat,place.lon)}};r.onSuccess{w=it;if(index==0)save(it)}.onFailure{err=it.message}}
  LazyColumn(Modifier.fillMaxSize().padding(horizontal=14.dp),verticalArrangement=Arrangement.spacedBy(12.dp),contentPadding=PaddingValues(bottom=24.dp)){if(err!=null)item{Text("Couldn't load weather: $err")};if(w==null&&err==null)item{Box(Modifier.fillParentMaxHeight(.7f),contentAlignment=Alignment.Center){CircularProgressIndicator()}};w?.let{x->
   item{Hero(x,index,count,onDelete)}
   if(x.alerts.isNotEmpty())item{Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.errorContainer),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(16.dp)){Text("⚠  Active weather alerts",fontSize=19.sp,fontWeight=FontWeight.Bold);x.alerts.take(4).forEach{Spacer(Modifier.height(5.dp));Text(it.event,fontWeight=FontWeight.Bold);Text(it.headline,fontSize=13.sp)}}}}
   item{Section("Next 24 hours"){LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(x.hours.take(24)){h->Card(shape=RoundedCornerShape(18.dp)){Column(Modifier.width(105.dp).padding(10.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(hour(h.time),fontSize=12.sp);Text(weatherIcon(h.code),fontSize=28.sp);Text("${h.temp.toInt()}°",fontSize=23.sp,fontWeight=FontWeight.Bold);Text("☂ ${h.pop}%",fontSize=12.sp);Text("${WeatherRepository.compass(h.windDir)} ${h.wind.toInt()} mph",fontSize=11.sp)}}}}}}
   item{Section("10-day forecast"){Text("Low     Daily temperature range     High",fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(4.dp));val min=x.days.minOfOrNull{it.lo}?:0.0;val max=x.days.maxOfOrNull{it.hi}?:100.0;x.days.forEach{d->DailyRow(d,min,max)}}}
   item{Section("Details"){val h=x.hours.firstOrNull();Metric("Humidity",x.humidity.toDouble(),100.0,"${x.humidity}%",listOf(Color(0xFF64B5F6),Color(0xFF1565C0)));Metric("Wind / gust",x.gust.coerceAtLeast(x.wind),50.0,"${WeatherRepository.compass(x.windDir)} ${x.wind.toInt()} mph  •  gust ${x.gust.toInt()}",listOf(Color(0xFF80CBC4),Color(0xFF00897B)));Text("Pressure ${x.pressure.toInt()} hPa  •  Dew point ${h?.dew?.toInt()?:0}°F\nPrecipitation ${h?.precip?:0.0} in",fontSize=14.sp);Spacer(Modifier.height(10.dp));UvMeter(h?.uv?:0.0)}}
   item{Section("Air quality"){x.air?.let{AqiMeter(it.usAqi);Spacer(Modifier.height(8.dp));Text("PM2.5 ${"%.1f".format(it.pm25)} µg/m³  •  Ozone ${"%.0f".format(it.ozone)} µg/m³",fontSize=14.sp)}?:Text("Air-quality data unavailable")}}
   item{Section("Sun"){SunArc(x.days.firstOrNull())}}
   item{RadarCard{x.let{startActivity(android.content.Intent(this@MainActivity,RadarActivity::class.java).putExtra("lat",it.lat).putExtra("lon",it.lon))}}}
  }}
 }
 @Composable private fun Hero(x:Weather,index:Int,count:Int,onDelete:()->Unit){val night=isNight(x.days.firstOrNull());val colors=if(night) listOf(Color(0xFF172554),Color(0xFF334155)) else when(x.code){in 51..99->listOf(Color(0xFF355C7D),Color(0xFF6C7A89));in 1..3->listOf(Color(0xFF4B79A1),Color(0xFF8CBED6));else->listOf(Color(0xFF1976D2),Color(0xFF64B5F6))};Card(shape=RoundedCornerShape(28.dp)){Column(Modifier.fillMaxWidth().background(Brush.linearGradient(colors)).padding(20.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.name,color=Color.White,fontSize=24.sp,fontWeight=FontWeight.Bold);if(count>1)Text("Swipe left or right for saved locations",color=Color.White.copy(.8f),fontSize=11.sp)};if(index>0)TextButton(onClick=onDelete){Text("Remove",color=Color.White)}};Row(verticalAlignment=Alignment.CenterVertically){Text("${x.currentTemp.toInt()}°",color=Color.White,fontSize=70.sp,fontWeight=FontWeight.Light);Spacer(Modifier.weight(1f));Text(weatherIcon(x.code),fontSize=62.sp)};Text(WeatherRepository.label(x.code),color=Color.White,fontSize=20.sp,fontWeight=FontWeight.Medium);Text("Feels ${x.apparent.toInt()}°  •  Humidity ${x.humidity}%",color=Color.White.copy(.92f));Text("Wind ${WeatherRepository.compass(x.windDir)} ${x.wind.toInt()} mph  •  Gust ${x.gust.toInt()} mph",color=Color.White.copy(.92f),fontSize=13.sp)}}}
 @Composable private fun DailyRow(d:Day,min:Double,max:Double){Column(Modifier.fillMaxWidth().padding(vertical=6.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(day(d.date),Modifier.width(70.dp),fontWeight=FontWeight.Medium);Text(weatherIcon(d.code),fontSize=23.sp,modifier=Modifier.width(38.dp));Text(WeatherRepository.label(d.code),Modifier.weight(1f),fontSize=13.sp);Text("☂ ${d.pop}%",fontSize=12.sp);Spacer(Modifier.width(8.dp));Text("${d.lo.toInt()}°",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.width(5.dp));Box(Modifier.width(55.dp).height(7.dp).clip(CircleShape).background(MaterialTheme.colorScheme.surfaceVariant)){val span=(max-min).coerceAtLeast(1.0);val start=((d.lo-min)/span).toFloat().coerceIn(0f,1f);val width=((d.hi-d.lo)/span).toFloat().coerceIn(.08f,1f);Box(Modifier.fillMaxHeight().fillMaxWidth(width).offset(x=(55*start).dp).clip(CircleShape).background(Brush.horizontalGradient(listOf(Color(0xFF64B5F6),Color(0xFFFFB74D)))))};Spacer(Modifier.width(5.dp));Text("${d.hi.toInt()}°",fontWeight=FontWeight.Bold)}}}
 @Composable private fun RadarCard(open:()->Unit){Card(onClick=open,shape=RoundedCornerShape(24.dp)){Box(Modifier.fillMaxWidth().height(125.dp).background(Brush.linearGradient(listOf(Color(0xFF183B56),Color(0xFF1B6B72),Color(0xFF4C956C))))){Box(Modifier.size(85.dp).offset(210.dp,20.dp).clip(CircleShape).background(Color(0x664CAF50)));Box(Modifier.size(55.dp).offset(175.dp,55.dp).clip(CircleShape).background(Color(0x66FFEB3B)));Column(Modifier.padding(18.dp)){Text("Animated radar",color=Color.White,fontSize=21.sp,fontWeight=FontWeight.Bold);Text("6 radar & forecast modes",color=Color.White.copy(.9f));Spacer(Modifier.weight(1f));Text("Tap to open  ›",color=Color.White,fontWeight=FontWeight.Bold)}}}}
 @Composable private fun Metric(name:String,value:Double,max:Double,text:String,colors:List<Color>){Text("$name  •  $text",fontWeight=FontWeight.Medium);Spacer(Modifier.height(5.dp));Box(Modifier.fillMaxWidth().height(9.dp).clip(CircleShape).background(MaterialTheme.colorScheme.surfaceVariant)){Box(Modifier.fillMaxHeight().fillMaxWidth((value/max).toFloat().coerceIn(.03f,1f)).background(Brush.horizontalGradient(colors)))};Spacer(Modifier.height(10.dp))}
 @Composable private fun IndicatorBar(fraction:Float,colors:List<Color>){BoxWithConstraints(Modifier.fillMaxWidth().height(20.dp)){Box(Modifier.fillMaxWidth().height(14.dp).align(Alignment.Center).clip(CircleShape).background(Brush.horizontalGradient(colors)));val f=fraction.coerceIn(0f,1f);Box(Modifier.offset(x=(maxWidth*f-6.dp).coerceIn(0.dp,maxWidth-12.dp)).align(Alignment.CenterStart).size(12.dp).clip(CircleShape).background(Color.White).padding(2.dp)){Box(Modifier.fillMaxSize().clip(CircleShape).background(Color.Black))}}}
 @Composable private fun SunArc(d:Day?){if(d==null){Text("Sun data unavailable");return};val sr=d.sunrise.substringAfter("T");val ss=d.sunset.substringAfter("T");val progress=runCatching{val sunrise=LocalDateTime.parse(d.sunrise);val sunset=LocalDateTime.parse(d.sunset);val now=LocalDateTime.now();when{now<=sunrise->0f;now>=sunset->1f;else->{val total=java.time.Duration.between(sunrise,sunset).toMinutes().coerceAtLeast(1);java.time.Duration.between(sunrise,now).toMinutes().toFloat()/total}}}.getOrDefault(0f);Text("☀  Sunrise $sr",fontWeight=FontWeight.Medium);Spacer(Modifier.height(6.dp));IndicatorBar(progress,listOf(Color(0xFF455A64),Color(0xFFFFC107),Color(0xFFFF9800),Color(0xFF455A64)));Spacer(Modifier.height(6.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Sunrise");Text("Current time",fontSize=12.sp,fontWeight=FontWeight.Bold);Text("Sunset")};Text("☾  Sunset $ss");Text("Today's max UV ${"%.1f".format(d.uv)}",fontSize=13.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}
 @Composable private fun AqiMeter(a:Int){val label=when{a<=50->"Good";a<=100->"Moderate";a<=150->"Unhealthy for sensitive groups";a<=200->"Unhealthy";a<=300->"Very unhealthy";else->"Hazardous"};Text("US AQI $a  •  $label",fontWeight=FontWeight.Bold);Spacer(Modifier.height(7.dp));IndicatorBar((a.coerceIn(0,500)/500f),listOf(Color(0xFF00A651),Color(0xFFFFD54F),Color(0xFFFF8F00),Color(0xFFE53935),Color(0xFF8E24AA)))}
 @Composable private fun UvMeter(uv:Double,title:String="UV index"){val label=when{uv<3->"Low";uv<6->"Moderate";uv<8->"High";uv<11->"Very high";else->"Extreme"};Text("$title ${"%.1f".format(uv)}  •  $label",fontWeight=FontWeight.Bold);Spacer(Modifier.height(6.dp));IndicatorBar((uv/15.0).toFloat().coerceIn(0f,1f),listOf(Color(0xFF2EAD5B),Color(0xFFFFD23F),Color(0xFFFF8C2A),Color(0xFFE53935),Color(0xFF8E24AA)))}

 @Composable private fun DonationDialog(onDismiss:()->Unit,onDonate:()->Unit){AlertDialog(onDismissRequest=onDismiss,title={Text("Help fund ClearSky")},text={Text("ClearSky is free, has no ads, and does not require an account. If you enjoy it, a voluntary donation helps support continued development. You can dismiss this and use every feature normally. This is the only automatic donation request ClearSky will show.")},confirmButton={Button(onClick=onDonate){Text("Donate via GitHub Sponsors")}},dismissButton={TextButton(onClick=onDismiss){Text("Not now")}})}
 @Composable private fun AboutCard(){Card(shape=RoundedCornerShape(22.dp)){Column(Modifier.fillMaxWidth().padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("About ClearSky",fontSize=20.sp,fontWeight=FontWeight.Bold,modifier=Modifier.align(Alignment.Start));Spacer(Modifier.height(8.dp));Text("Version ${BuildConfig.VERSION_NAME}",modifier=Modifier.align(Alignment.Start));Text("Free • No ads • No account • No analytics",fontSize=13.sp,color=MaterialTheme.colorScheme.onSurfaceVariant,modifier=Modifier.align(Alignment.Start));Spacer(Modifier.height(12.dp));androidx.compose.foundation.Image(painterResource(R.drawable.zeus_signature),contentDescription="!!ZuEs!! signature",modifier=Modifier.fillMaxWidth().heightIn(max=210.dp).clip(RoundedCornerShape(16.dp)),contentScale=ContentScale.Fit);Spacer(Modifier.height(8.dp));Text("Developed by !!ZuEs!!",fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));Text("Your saved locations and donation-reminder date stay on this device. ClearSky has no advertising or analytics SDK. Weather and radar requests still contact their data providers and therefore necessarily reveal the requesting IP address and requested forecast coordinates.",fontSize=12.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(12.dp));Button(onClick={openUrl("https://github.com/sponsors/cpugod55")},modifier=Modifier.fillMaxWidth()){Text("Donate via GitHub Sponsors")};OutlinedButton(onClick={openUrl("https://github.com/cpugod55/ClearSky-Weather")},modifier=Modifier.fillMaxWidth()){Text("ClearSky on GitHub")}}}}
 private fun openUrl(url:String){runCatching{startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(url)))}}
 private fun weatherIcon(c:Int)=when(c){0->"☀";1,2->"🌤";3->"☁";45,48->"🌫";in 51..57->"🌦";in 61..67->"🌧";in 71..77->"❄";in 80..82->"🌧";in 85..86->"🌨";in 95..99->"⛈";else->"☁"}
 private fun isNight(d:Day?):Boolean{if(d==null)return false;return runCatching{val now=LocalTime.now();val sr=LocalDateTime.parse(d.sunrise).toLocalTime();val ss=LocalDateTime.parse(d.sunset).toLocalTime();now<sr||now>ss}.getOrDefault(false)}
 private fun same(a:Place,b:Place)=abs(a.lat-b.lat)<.01&&abs(a.lon-b.lon)<.01
 private fun readPlaces():List<Place>{val p=getSharedPreferences("prefs",0);val la=p.getString("lat",null)?.toDoubleOrNull();val lo=p.getString("lon",null)?.toDoubleOrNull();val out=mutableListOf<Place>();if(la!=null&&lo!=null)out+=Place(p.getString("name","Current location")?:"Current location",la,lo);runCatching{val a=JSONArray(p.getString("saved_locations","[]"));for(i in 0 until a.length()){val o=a.getJSONObject(i);val x=Place(o.getString("name"),o.getDouble("lat"),o.getDouble("lon"));if(out.none{same(it,x)})out+=x}};return out}
 private fun addSaved(x:Place):List<Place>{val all=readPlaces().toMutableList();if(all.none{same(it,x)})all+=x;writeSaved(all.drop(1));return all}
 private fun removeSaved(x:Place):List<Place>{val all=readPlaces().filterNot{same(it,x)};writeSaved(all.drop(1));return all}
 private fun writeSaved(xs:List<Place>){val a=JSONArray();xs.forEach{a.put(JSONObject().put("name",it.name).put("lat",it.lat).put("lon",it.lon))};getSharedPreferences("prefs",0).edit().putString("saved_locations",a.toString()).apply()}
 private fun requestLocation(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED)locate() else perm.launch(arrayOf(Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_FINE_LOCATION))}
 private fun locate(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;fused.getCurrentLocation(Priority.PRIORITY_BALANCED_POWER_ACCURACY,CancellationTokenSource().token).addOnSuccessListener{l->if(l!=null)CoroutineScope(Dispatchers.IO).launch{val n=WeatherRepository.reverseName(l.latitude,l.longitude);getSharedPreferences("prefs",0).edit().putString("lat",l.latitude.toString()).putString("lon",l.longitude.toString()).putString("name",n).apply();withContext(Dispatchers.Main){recreate()}}}}
 private fun save(w:Weather){WeatherUiStore.save(this,w);WeatherStatusWorker.show(this,w);WeatherWidget.refreshAll(this)}
}
@Composable fun Section(title:String,body: @Composable () -> Unit){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(16.dp)){Text(title,fontSize=20.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));body()}}}
fun hour(s:String)=runCatching{LocalDateTime.parse(s).format(DateTimeFormatter.ofPattern("h a"))}.getOrDefault(s.takeLast(5))
fun day(s:String)=runCatching{LocalDate.parse(s).format(DateTimeFormatter.ofPattern("EEE M/d"))}.getOrDefault(s)
